# -*- coding: utf-8 -*-
"""08_Retrain_Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BfrC8nNbXaY5lMXrmr42fidGZPbEtqBw
"""

import warnings
warnings.filterwarnings("ignore")

#Load auxiliary functions
from FunctionsRetail import *

#Load Data
root = '/content/drive/MyDrive/02_RETAIL'
data_file_name = 'work.csv'
root_complete = root + '/02_Data/03_Work/' + data_file_name
df = pd.read_csv(root_complete,sep=',',parse_dates=['date'],index_col='date')

#Seldct only the used ones
final_variables = ['store_id',
                     'item_id',
                     'event_name_1',
                     'month',
                     'sell_price',
                     'wday',
                     'weekday',
                     'sales']

df = df[final_variables]

df_step1 = data_quality(df)
df_step2 = create_variables(df_step1)

launch_training(df_step2)